version: "3.1"
services:
  ausleihservice:
    build: ./ausleih-service/
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    depends_on:
      - "ausleihdb"
      - "propay"

  ausleihdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./ausleihdb:/var/lib/postgresql/data

  propay:
    image: propra/propay
    volumes:
      - ./propaydb:/code/data
